sudo: required
dist: xenial
language: go
go_import_path: github.com/CanonicalLtd/serial-vault
go:
  - 1.6
env:
  matrix:
    - TEST_SUITE="--static"
    - TEST_SUITE="--unit"

before_install:
    - go get github.com/cheggaaa/pb
    - go get gopkg.in/macaroon.v1
    - go get gopkg.in/retry.v1
    - go get gopkg.in/tomb.v2
    - go get gopkg.in/check.v1
    - go get github.com/golang/lint/golint
    - go get github.com/client9/misspell/cmd/misspell
    - go get -u github.com/gordonklaus/ineffassign
    - go get -u github.com/alexkohler/nakedret
    - sh ./get-deps.sh

install:
    - echo $GOPATH
    - echo "Remaining install is done by the test script."
    - true
script: sh -v ./run-checks $TEST_SUITE
