dist: focal

jobs:
  include:
    - stage: test
      name: "Golang build and tests"
      language: go
      env:
        - GO111MODULE=on
      go:
        - 1.13.x
      before_script:
        - go mod vendor
      script: 
        - make build
        - make test
    
    - stage: test
      name: "Node.js tests"
      language: node_js
      node_js:
        - lts/*
      env:
        - NODE_ENV=test
      script:
        - make test-frontend-ci
