# Path to the private key file
privateKeyPath: "./TestKey.asc"

# Identity Vault version
version: "0.2.0"
title: "Identity Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Backend database details
driver: "postgres"
datasource: "dbname=identity-vault"

# Signing Key Store
keystore: "filesystem"
keystorePath: "./keystore"
