title: "Serial Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Service mode: signing or admin
mode: signing

# Path to the assets (${docRoot}/static)
docRoot: "."

# Backend database details
driver: "postgres"
# datasource: "dbname=serialvault sslmode=disable"
datasource: "postgres://vault:vault@localhost:5432/vault?sslmode=disable"


# Signing Key Store
keystore: "filesystem"
keystorePath: "./keystore"

# For Database
keystore: "database"
# CHANGEME: This keystoreSecret value is only a sample. Please provide another custom generated one
keystoreSecret: "uXeid2iy1RoX0Io0Beigae3iza5oechu"

# For TPM 2.0
#keystore: "tpm2.0"
#keystorePath: "./keystore"
#keystoreSecret: "this needs to be 32 bytes long!!"

# 32 bytes long key to protect server from cross site request forgery attacks
# CHANGEME: This csrfAuthKey value is only a sample. Please provide another custom generated one
csrfAuthKey: "2E3zYnVYUfDLRLV/ne8M6v1jyB/37XBL9ORnN3Kgb04uSFalr2ygReVsOt0PaGEIRuID10TePBje5xdBIOEjqq=="

# http://localhost:8081/login
# Return URL of the service (needed for OpenID)
urlHost: "localhost:8081"
urlScheme: http

# Enable user authentication using Ubuntu SSO
enableUserAuth: False

# Key needed for USSO. 
# CHANGEME: This jwtSecret is only a sample. Please provide another custom generated value
# jwtSecret: ""

# Factory sync only
syncUrl: "https://serial-vault-partners.canonical.com/api/"
syncUser: "lpuser"
syncAPIKey: "user-apikey"
