title: "Serial Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Service mode: signing or admin or system-user
mode: signing

# Path to the assets (${docRoot}/static)
docRoot: "."

# Backend database details
driver: "postgres"
datasource: "dbname=serialvault sslmode=disable"

# Signing Key Store
#keystore: "filesystem"
#keystorePath: "./keystore"

# For Database
keystore: "database"
keystoreSecret: "secret code to encrypt the auth-key hash"

# For TPM 2.0
#keystore: "tpm2.0"
#keystorePath: "./keystore"
#keystoreSecret: "this needs to be 32 bytes long!!"

# Valid API keys
apiKeys:
    - U2VyaWFsIFZhdWx0Cg

# 32 bytes long key to protect server from cross site request forgery attacks
csrfAuthKey: "2E6ZYnVYUfDLRLV/ne8M6v1jyB/376BL9ORnN3Kgb04uSFalr2ygReVsOt0PaGEIRuID10TePBje5xdjIOEjQQ=="

# Base URL of the service (needed for OpenID)
baseURL: http://serial-vault
