title: "Serial Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Service mode: signing or admin
mode: signing

# Path to the assets (${docRoot}/static)
docRoot: "."

# Backend database details
driver: "postgres"
datasource: "postgres://vault:vault@localhost:5432/vault?sslmode=disable"

# Signing Key Store
# keystore: "filesystem"
# keystorePath: "./keystore"

# For Database
keystore: "database"
keystoreSecret: "KEYSTORE_SECRET"

# For TPM 2.0
#keystore: "tpm2.0"
#keystorePath: "./keystore"
#keystoreSecret: "this needs to be 32 bytes long!!"

# Valid API keys
apiKeys:
    - API_KEY

# 32 bytes long key to protect server from cross site request forgery attacks
csrfAuthKey: "32_BYTES_LONG_CSRF_AUTH_KEY"
