# Identity Vault version
version: "0.2.0"
title: "Identity Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Backend database details
driver: "postgres"
datasource: "dbname=identity-vault"

# Signing Key Store
#keystore: "filesystem"
#keystorePath: "./keystore"
keystore: "tpm2.0"
keystorePath: "/dev/pts/19"
