name: serial-vault-server
version: 1.7
summary: Serial Vault Server
description: Service for the Serial Vault that signs serial assertions.
confinement: strict
grade: stable

apps:
    service:
      command: bin/snap-run-service
      plugs:
        - network
        - network-bind
      daemon: simple
    config:
      command: bin/set-config
    admin:
      command: bin/snap-run-admin
      plugs:
        - network
parts:
    service:
      plugin: go
      source: git://github.com/CanonicalLtd/serial-vault
      go-importpath: github.com/CanonicalLtd/serial-vault

    bin:
      source: ../../bin
      plugin: dump
      organize:
        "*": bin/
    static:
      source: ../../static
      plugin: dump
      organize:
        "*": static/
    # Private key for the vaultclient
    keystore:
      source: ../../keystore
      plugin: dump
      organize:
        TestDeviceKey.asc: keystore/TestDeviceKey.asc
