version: '2'
services:
  db:
    image: postgres
    env_file:
      - ./env
  web:
    build: ..
    depends_on:
      - db
    env_file:
      - ./env
    environment:
      - CSRF_SECURE=$CSRF_SECURE
    ports:
      - "8080:8080"
      - "8081:8081"
