db:
  image: postgres
  volumes:
      - ./db/postgres-setup.sql:/docker-entrypoint-initdb.d/setup.sql
  environment:
      POSTGRES_PASSWORD: ubuntu
web:
  build: ..
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - db
