title: "Serial Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Path to the assets (${docRoot}/static)
docRoot: "."

# Backend database details
driver: "postgres"
datasource: "postgres://postgres:ubuntu@db:5432/identityvault?sslmode=disable"

# Signing Key Store
keystore: "filesystem"
keystorePath: "./keystore"

# For Database
#keystore: "database"
#keystoreSecret: "secret code to encrypt the auth-key hash"

# For TPM 2.0
#keystore: "tpm2.0"
#keystorePath: "./keystore"
#keystoreSecret: "this needs to be 32 bytes long!!"

# Valid API keys
apiKeys:
    - U2VyaWFsIFZhdWx0Cg
