# Identity Vault version
version: "0.2.0"
title: "Identity Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Backend database details
driver: "postgres"
datasource: "postgres://postgres:ubuntu@db:5432/identityvault?sslmode=disable"

# Signing Key Store
keystore: "filesystem"
keystorePath: "./keystore"
