title: "Serial Vault"
logo: "/static/images/logo-ubuntu-white.svg"

# Path to the assets (${docRoot}/static)
docRoot: "."

# Backend database details
driver: "postgres"
datasource: "postgres://POSTGRES_USER:POSTGRES_PASSWORD@POSTGRES_HOST:POSTGRES_PORT/POSTGRES_DB?sslmode=disable"

# Signing Key Store
# keystore: "filesystem"
# keystorePath: "./keystore"

# For Database
keystore: "database"
keystoreSecret: "KEYSTORE_SECRET"

# For TPM 2.0
#keystore: "tpm2.0"
#keystorePath: "./keystore"
#keystoreSecret: "this needs to be 32 bytes long!!"

# Valid API keys
apiKeys:
    - API_KEY
