title: "{{ title }}"
logo: "{{ logo }}"
docRoot: "{{ docRoot }}"
mode: "{{ mode }}"
portAdmin: "{{ portAdmin }}"
portSigning: "{{ portSigning }}"
driver: "{{ dbdriver }}"
datasource: "{{ maindb }}"
keystore: "{{ keystore }}"
keystoreSecret: "{{ keystoreSecret }}"
csrfAuthKey: "{{ csrfAuthKey }}"
urlHost: "{{ urlHost }}"
urlScheme: "{{ urlScheme }}"
enableUserAuth: {{ enableUserAuth }}
jwtSecret: "{{ jwtSecret }}"
syncUrl: "{{ syncUrl }}"
syncUser: "{{ syncUser }}"
syncAPIKey: "{{ syncAPIKey }}"
