name: factory-serial-vault
version: 0.2
summary: Serial Vault for a Factory
description: Restricted serial vault for deployment in a factory with limited Internet connection
confinement: strict
grade: stable

apps:
  # Apache daemon
  apache:
    command: run-httpd -k start -DFOREGROUND
    stop-command: run-httpd -k stop
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

  # Apache Utilities
  enable-https:
    command: enable-https
    plugs: [network, network-bind]
  disable-https:
    command: disable-https
    plugs: [network, network-bind]
  renew-certs:
    command: renew-certs
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind]

  # Serial-Vault Services
  signing:
    command: bin/snap-run-signing-service
    plugs:
      - network
      - network-bind
    daemon: simple
  sync:
    command: bin/snap-run-sync
    daemon: simple
    plugs:
      - network

  # Serial-Vault Configuration and Utilities
  factory:
    command: bin/factory
    plugs:
      - network
  serviceinit:
    command: bin/serviceinit.sh
    plugs:
    - network
    - network-bind
  config:
    command: bin/set-config

parts:
  service:
      plugin: go
      source-tag: go1.9.4
      source-depth: 1
      source: .
      go-importpath: github.com/CanonicalLtd/serial-vault
      build: |
        export GOPATH=$(cd ../go && pwd)
        GOBIN=$GOPATH/bin
        PKG=github.com/CanonicalLtd/serial-vault
        mkdir -p $GOBIN
        cd $GOPATH/src/$PKG
        ./get-deps.sh
        go install ./...
      install: |
        GOPATH=$(cd ../go && pwd)
        GOBIN=$GOPATH/bin
        PKG=github.com/CanonicalLtd/serial-vault
        mkdir -p $SNAPCRAFT_PART_INSTALL/bin
        cp $GOBIN/serial-vault $SNAPCRAFT_PART_INSTALL/bin
        cp $GOBIN/factory $SNAPCRAFT_PART_INSTALL/bin
      after: [go]
  bin:
      source: bin
      plugin: dump
      organize:
        "*": bin/
  serviceinit:
      source: factory-serial-vault/bin
      plugin: dump
      organize:
        "*": bin/

  apache:
    plugin: apache
    source: https://archive.apache.org/dist/httpd/httpd-2.4.25.tar.bz2
    source-checksum: sha1/bd6d138c31c109297da2346c6e7b93b9283993d2

    # The built-in Apache modules to enable
    modules:
      - headers
      - proxy
      - proxy_http
      - proxy_wstunnel
      - setenvif
      - env
      - rewrite
      - mime
      - dir
      - authz_core
      - unixd
      - alias
      - ssl
      - socache_shmcb
      - log_config

    filesets:
      exclude:
        - -man
        - -manual
        - -htdocs
        - -include
        - -build
        - -conf/httpd.conf
        - -conf/magic
        - -conf/original
        - -conf/extra
        - -bin/apachectl
        - -bin/envvars*
        - -bin/ab
        - -bin/apxs
        - -bin/checkgid
        - -bin/dbmmanage
        - -bin/fcgistarter
        - -bin/htcacheclean
        - -bin/htdbm
        - -bin/htdigest
        - -bin/htpasswd
        - -bin/httxt2dbm
        - -bin/logresolve
        - -bin/rotatelogs
    stage:
      - $exclude
    prime:
      - $exclude

  apache-customizations:
    plugin: dump
    source: factory-serial-vault/src/apache
    organize:
      html/*: static/